
base_model:
    type: Llama
    path: /home/yuhaida/huggingface/hub/models--huggyllama--llama-7b/snapshots/4782ad278652c7c71b72204d462d6d01eaaf7549
    torch_dtype: torch.float16
    tokenizer_mode: fast
    device_map: "cuda:0"
quant: False


eval:
  device: cuda
  tasks: [
    {
      task: acc,
      datasets: [winogrande, arc_easy, arc_challenge, piqa, mmlu, openbookqa, mathqa],
      batch_size: auto,
      num_fewshot: 2
    },
    {
      task: ppl,
      datasets: [wikitext2],
      download: True,
      seqlen: 2048,
      nsamples: all
    },
    {
      task: ppl,
      datasets: [c4],
      download: True,
      seqlen: 2048,
      nsamples: all
    }
  ]

save: /home/yuhaida/llama_7b/output/llama27b_miom_2