base_model:
    type: Llama
    path: /netcache/huggingface/llama-2-7b-hf/
    torch_dtype: torch.float16
    tokenizer_mode: fast
    device_map: "cuda:0"
quant:
    method: gptq
    skip_layers: [ lm_head ]
    seqlen: 2048
    device: cuda
    weight:
      wbit: 3
      abit: 16
      offload: cpu
      block_sequential: True
      layer_sequential: True
      w_qtype: per_group
      groupsize: 128
      blocksize: 128
      percdamp: 0.01
      actorder: False
    special:
      actorder: True
      static_groups: False
      percdamp: 0.01
      blocksize: 128
      true_sequential: True
    data:
      name: cola
      force_regenerate: True
      nsamples: 128
      seqlen: 2048
      download: True
      batch_size: 4
      split: validation
      seed: 42
eval:
  device: cuda
  tasks: [
    {
      task: acc,
      datasets: [winogrande, arc_easy, arc_challenge, piqa],
      batch_size: auto,
      num_fewshot: 2
    },
    {
      task: ppl,
      datasets: [c4],
      download: True,
      seqlen: 2048,
      nsamples: all
    }
  ]
save: /home/yejinyu/llama2_7b/output/llama27b_miom_2
