base_model:
    type: Llama
    path: /netcache/huggingface/llama2_7b/
    torch_dtype: auto
    tokenizer_mode: fast
quant:
    method: billm
    skip_layers: [ lm_head ]
    seqlen: 2048
    device: cuda
    weight:
      wbit: 1
      #abit: Precision.FP16
      salient_metric: hessian
      disable_gptq: False
      offload: cpu
      block_sequential: True
      layer_sequential: True
      w_qtype: per_group
      groupsize: 128
      blocksize: 128
      percdamp: 0.01
      actorder: False
      order: 2

    data:
      name: c4
      split: train
      nsamples: 128       
      seqlen: 2048
      download: False
      path: /netcache/huggingface/c4_local/c4-train.00000-of-01024.json.gz
      batch_size: 32
      seed: 42


eval:
    # 评测任务类型
    tasks: [Commonsense_Reasoning]

    # 评测数据集 
    datasets: [winogrande, hellaswag, arc_easy, arc_challenge]
    # datasets: [commonsense_qa, piqa, social_iqa]

    download: False
    path: /netcache/huggingface/c4_local/c4-validation.00000-of-00008.json.gz,
    seq_len: 2048
    batch_size: 32
    num_fewshot: 5
    nsamples: all
    device: cuda
    seqlen: 2048

# ============================================
# 保存路径 
save: /netcache/zcx2/compress_models/llama2_7b/llama2_7b_billm_w1/
